export const ROUTE = {
  HOME: '/',
  STUDY: '/study',
  SERVICES: '/services',
  MASTERS: '/masters',
  MASTER: '/masters/:id',
  CANCELVISIT: '/cancel',
  CONTACTS: '/contacts',
  FEEDBACK: '/feedbacks',
  VACANCIES: '/vacancies',
  COMMENTS: '/comments',
  FEEDBACKMORE: '/feedbacks/more',
  CLIENTFEEDBACK: '/feedbacks/client',
  CANCELSTUDY: '/study/cancel',
};
